spring:
  datasource:
    url: jdbc:h2:mem:company_analyzer
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

vacancy:
  page:
    size: 100
    #sizeInUrl shows after overcoming what number Indeed flows the vacancy page.
    #With a real number of vacancies has nothing to do, because caused by the bag on Indeed.
    sizeInUrl: 150